# permissions for end users to view smbvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbvolume-viewer-role
rules:
- apiGroups:
  - storage.sergio.link
  resources:
  - smbvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.sergio.link
  resources:
  - smbvolumes/status
  verbs:
  - get
